/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edd.practica1_201314655;

/**
 *
 * @author Personal
 */
public class AgregarPlantas extends javax.swing.JFrame {

    /**
     * Creates new form AgregarPlantas
     */
    public AgregarPlantas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plants");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("AgregarPlantas"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/practica1_201314655/Images/Plantas/planta1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urlimage(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 70, 100, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/practica1_201314655/Images/Plantas/planta2.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urlimage2(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 70, 110, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/practica1_201314655/Images/Plantas/planta3.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urlimage3(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(310, 50, 110, 150);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edd/practica1_201314655/Images/Plantas/planta4.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urlimage4(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(440, 60, 100, 130);

        jLabel5.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel5.setText("URL Imagen:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 200, 90, 30);

        jTextField1.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jTextField1.setName("txtImagenPlanta"); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(130, 200, 400, 30);
        jTextField1.getAccessibleContext().setAccessibleName("txtImagenPlanta");

        jLabel6.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel6.setText("Nombre:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 250, 60, 20);

        jTextField2.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(130, 240, 140, 30);

        jLabel7.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel7.setText("Puntos: ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 290, 60, 20);

        jTextField3.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(130, 280, 140, 30);

        jLabel8.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel8.setText("Ataque:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 330, 60, 20);

        jTextField4.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(130, 320, 140, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(60, 383, 100, 30);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Agregar");
        jPanel1.add(jButton2);
        jButton2.setBounds(450, 380, 100, 30);

        jLabel9.setFont(new java.awt.Font("Aharoni", 0, 36)); // NOI18N
        jLabel9.setText("Agregar Plantas");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(150, 20, 300, 40);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 430));

        getAccessibleContext().setAccessibleName("AgregarPlantas");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urlimage(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urlimage
         jTextField1.setText("/edd/practica1_201314655/Images/Plantas/planta1.png");
         // TODO add your handling code here:
    }//GEN-LAST:event_urlimage

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void urlimage2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urlimage2
         jTextField1.setText("/edd/practica1_201314655/Images/Plantas/planta2.png");       // TODO add your handling code here:
    }//GEN-LAST:event_urlimage2

    private void urlimage3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urlimage3
         jTextField1.setText("/edd/practica1_201314655/Images/Plantas/planta3.png");        // TODO add your handling code here:
    }//GEN-LAST:event_urlimage3

    private void urlimage4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urlimage4
         jTextField1.setText("/edd/practica1_201314655/Images/Plantas/planta4.png");        // TODO add your handling code here:
    }//GEN-LAST:event_urlimage4

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         jTextField1.setText("");
         jTextField2.setText("");
         jTextField3.setText("");
         jTextField4.setText("");
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPlantas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPlantas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
